# Generated by Django 5.2.7 on 2025-10-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
